export type Language = 'en' | 'ru';

type Translations = { [key: string]: string };

const translations: { [lang in Language]: Translations } = {
    en: {
        // Splash screen
        bootSeq1: '> AETHER-DRIVE SYNC... [OK]',
        bootSeq2: '> CALIBRATING NAV-SENSORS... [OK]',
        bootSeq3: '> LOADING STAR-CHART... [SECTOR 1]',
        bootSeq4: '> ENGAGING PILOT INTERFACE...',
        controlsSteer: '[ARROWS] or [WASD] :: Steer & Thrust',
        controlsBrake: '[S] or [ARROW DOWN] :: Retro Thrusters',
        controlsLaser: '[SPACEBAR] :: Fire Laser',
        controlsMissile: '[SHIFT] :: Fire Homing Missile',
        controlsJump: 'FLY INTO HYPERSPACE GATE TO JUMP ({cost} Crystals)',
        engageButton: '> ENGAGE <',
        scrollerText: 'SIGNAL BOUNCING FROM A GHOST RELAY... THEY SAY THE CORE SYSTEMS ARE A GRAVEYARD... BUT THE VOID PAYS WELL FOR THOSE WHO DARE TO DANCE WITH GHOSTS... FLY TRUE, DRIFTER, YOUR LEGEND IS UNWRITTEN...',
        // Game Over
        gameOverTitle: 'SIGNAL LOST',
        gameOverLocation: 'Last known location: {sector}',
        gameOverReason: 'Reason: [Life Support Offline]',
        gameOverRestart: '> RE-ENGAGE <',
        // HUD
        hudHull: 'Hull',
        hudAmmo: 'Capacitor',
        hudMissiles: 'Missiles',
        hudCrystals: 'Crystals',
        hudDollars: 'Dollars',
        hudHyperspace: 'Hyperspace',
        hudJumpReady: 'Gate Travel Ready',
        hudJumpCharging: 'Need {cost} Crystals',
        hudFireMissile: '[SHIFT] Fire Missile',
        hudGravity: 'G-Force',
        // Mission
        missionIncoming: 'Active Contract',
        missionCompleteTitle: 'Contract Complete!',
        missionReward: 'Payment: {dollars}$ & {missiles} Missile(s)',
        missionRewardDollarsOnly: 'Payment: {dollars}$',
        missionObjectiveDestroy: 'HUNT: {targetName}',
        missionObjectiveCollect: 'COLLECT: T-Crystals ({collected}/{amount})',
        // Station & Prompts
        promptDockStation: 'Press [E] to Dock with Erebus Station',
        stationMenuTitle: 'Erebus Station',
        stationMenuDesc: 'We pay in dollars. Keep the crystals for yourself - you\'ll need them for the jump drive.',
        missionTitleBounty: 'Bounty: The Black Widow',
        missionDescBounty: 'Hunt down the notorious pirate Thanaia "Black Widow" Volt. Last seen operating out of the Tau Ceti system. She is considered armed and extremely dangerous.',
        missionTitleCollect: 'Urgent Supply Run',
        missionDescCollect: "Erebus Station's life support is running low on critical T-Crystals. We need an independent contractor for an urgent collection run. We'll pay, you keep the crystals.",
        missionAccept: 'Accept Contract',
        stationTabContracts: 'Contracts',
        stationTabUpgrades: 'Upgrades',
        upgradeHullName: 'Reinforced Hull',
        upgradeHullDesc: 'Increases maximum hull integrity by 25.',
        upgradeEngineName: 'Tuned Thrusters',
        upgradeEngineDesc: 'Increases thrust and maneuverability.',
        upgradeWeaponName: 'Optimized Capacitors',
        upgradeWeaponDesc: 'Increases weapon fire rate.',
        upgradeAmmoCapName: 'Expanded Magazine',
        upgradeAmmoCapDesc: 'Increases maximum ammo capacity by 5.',
        upgradeMagnetName: 'Graviton Collector',
        upgradeMagnetDesc: 'Increases the range of the resource magnet.',
        upgradeLevel: 'Level {current}/{max}',
        upgradeButton: 'Upgrade',
        upgradeCost: 'Cost: {cost}$',
        upgradeMaxLevel: 'Max Level',
        // Radar
        radarTitle: 'Radar',
        radarTypeYou: 'You',
        radarTypeStar: 'Star',
        radarTypePlanet: 'Planet',
        radarTypeAsteroid: 'Asteroid',
        radarTypeCrystal: 'Crystal',
        radarTypeGate: 'Gate',
        // Nav Arrow
        navStar: 'Star',
        navCrystal: 'Crystal',
        navGate: 'Hyperspace Gate',
        // Star Map
        mapTitle: 'Stellar Navigation',
        mapSystemInfo: 'System Intel',
        mapThreatLevel: 'Threat Level: {level}',
        mapSelectSystem: 'Select a highlighted system for details.',
        mapJumpButton: 'INITIATE JUMP',
        mapJumpCost: 'Cost: {cost} Crystals',
        mapJumpInsufficient: 'INSUFFICIENT CRYSTALS',
        mapNoRoute: 'No route calculated. Set a mission objective first.',
        mapSelectAdjacent: 'Select a connected system to plot a route.',
    },
    ru: {
        // Splash screen
        bootSeq1: '> СИНХРОНИЗАЦИЯ ЭФИР-ПРИВОДА... [OK]',
        bootSeq2: '> КАЛИБРОВКА НАВ-СЕНСОРОВ... [OK]',
        bootSeq3: '> ЗАГРУЗКА ЗВЕЗДНОЙ КАРТЫ... [СЕКТОР 1]',
        bootSeq4: '> ПОДКЛЮЧЕНИЕ ИНТЕРФЕЙСА ПИЛОТА...',
        controlsSteer: '[СТРЕЛКИ] или [WASD] :: Управление и тяга',
        controlsBrake: '[S] или [СТРЕЛКА ВНИЗ] :: Реверсивные двигатели',
        controlsLaser: '[ПРОБЕЛ] :: Огонь из лазера',
        controlsMissile: '[SHIFT] :: Пуск самонаводящейся ракеты',
        controlsJump: 'ВЛЕТИТЕ В ГИПЕРВРАТА ДЛЯ ПРЫЖКА ({cost} кристалла(ов))',
        engageButton: '> НАЧАТЬ <',
        scrollerText: 'СИГНАЛ ОТРАЖАЕТСЯ ОТ РЕЛЕ-ПРИЗРАКА... ГОВОРЯТ, ЦЕНТРАЛЬНЫЕ СИСТЕМЫ - ЭТО КЛАДБИЩЕ... НО ПУСТОТА ЩЕДРО ПЛАТИТ ТЕМ, КТО СМЕЕТ ТАНЦЕВАТЬ С ПРИЗРАКАМИ... ДЕРЖИ КУРС, ДРИФТЕР, ТВОЯ ЛЕГЕНДА ЕЩЕ НЕ НАПИСАНА...',
        // Game Over
        gameOverTitle: 'СИГНАЛ ПОТЕРЯН',
        gameOverLocation: 'Последнее известное местоположение: {sector}',
        gameOverReason: 'Причина: [Система жизнеобеспечения отключена]',
        gameOverRestart: '> ПЕРЕЗАПУСК <',
        // HUD
        hudHull: 'Корпус',
        hudAmmo: 'Конденсатор',
        hudMissiles: 'Ракеты',
        hudCrystals: 'Кристаллы',
        hudDollars: 'Доллары',
        hudHyperspace: 'Гиперпрыжок',
        hudJumpReady: 'Готов к прыжку',
        hudJumpCharging: 'Нужно {cost} кристалла(ов)',
        hudFireMissile: '[SHIFT] Пуск ракеты',
        hudGravity: 'Перегрузка',
        // Mission
        missionIncoming: 'Активный контракт',
        missionCompleteTitle: 'Контракт выполнен!',
        missionReward: 'Оплата: {dollars}$ и {missiles} ракета(ы)',
        missionRewardDollarsOnly: 'Оплата: {dollars}$',
        missionObjectiveDestroy: 'ОХОТА: {targetName}',
        missionObjectiveCollect: 'СБОР: Т-Кристаллы ({collected}/{amount})',
        // Station & Prompts
        promptDockStation: 'Нажмите [E] для стыковки со станцией "Эребус"',
        stationMenuTitle: 'Станция "Эребус"',
        stationMenuDesc: 'Мы платим в долларах. Кристаллы оставьте себе - они вам понадобятся для прыжкового двигателя.',
        missionTitleBounty: 'Награда: Чёрная Вдова',
        missionDescBounty: 'Выследить и уничтожить печально известную пиратку Танаис "Чёрная Вдова" Вольт. Последний раз замечена в системе Тау Кита. Считается вооруженной и чрезвычайно опасной.',
        missionTitleCollect: 'Срочная доставка',
        missionDescCollect: 'Системе жизнеобеспечения станции "Эребус" не хватает Т-Кристаллов. Требуется независимый подрядчик для срочного сбора. Мы платим, а кристаллы вы оставляете себе.',
        missionAccept: 'Принять контракт',
        stationTabContracts: 'Контракты',
        stationTabUpgrades: 'Улучшения',
        upgradeHullName: 'Усиленный корпус',
        upgradeHullDesc: 'Увеличивает максимальную прочность корпуса на 25.',
        upgradeEngineName: 'Настроенные двигатели',
        upgradeEngineDesc: 'Увеличивает тягу и маневренность.',
        upgradeWeaponName: 'Оптимизированные конденсаторы',
        upgradeWeaponDesc: 'Увеличивает скорострельность.',
        upgradeAmmoCapName: 'Расширенный магазин',
        upgradeAmmoCapDesc: 'Увеличивает максимальный боезапас на 5.',
        upgradeMagnetName: 'Гравитонный сборщик',
        upgradeMagnetDesc: 'Увеличивает дальность притягивания ресурсов.',
        upgradeLevel: 'Уровень {current}/{max}',
        upgradeButton: 'Улучшить',
        upgradeCost: 'Стоимость: {cost}$',
        upgradeMaxLevel: 'Макс. уровень',
        // Radar
        radarTitle: 'Радар',
        radarTypeYou: 'Вы',
        radarTypeStar: 'Звезда',
        radarTypePlanet: 'Планета',
        radarTypeAsteroid: 'Астероид',
        radarTypeCrystal: 'Кристалл',
        radarTypeGate: 'Врата',
        // Nav Arrow
        navStar: 'Звезда',
        navCrystal: 'Кристалл',
        navGate: 'Гиперврата',
        // Star Map
        mapTitle: 'Звёздная навигация',
        mapSystemInfo: 'Данные о системе',
        mapThreatLevel: 'Уровень угрозы: {level}',
        mapSelectSystem: 'Выберите выделенную систему для получения данных.',
        mapJumpButton: 'НАЧАТЬ ПРЫЖОК',
        mapJumpCost: 'Стоимость: {cost} кристалла(ов)',
        mapJumpInsufficient: 'НЕДОСТАТОЧНО КРИСТАЛЛОВ',
        mapNoRoute: 'Маршрут не проложен. Сначала возьмите задание.',
        mapSelectAdjacent: 'Выберите соседнюю систему для прокладки маршрута.',
    }
};

export const createTranslator = (lang: Language) => (key: string, params: { [key: string]: string | number } = {}): string => {
    let str = translations[lang]?.[key] || translations['en'][key] || key;
    for (const p in params) {
        str = str.replace(`{${p}}`, String(params[p]));
    }
    return str;
};